# Site settings
title: Grabcode
email: alex@grabcode.fr
description: "© 2015 Alexandre Girard"
baseurl: ""
url: "http://grabcode.fr"
twitter_username: grabthecode
github_username:  grabcode

# Build settings
markdown: kramdown
permalink: pretty
#sass:
  #style: :compressed

collections:
  projects:
    output: true
  cheatsheets:
    output: true
