# Site settings
title: Grabcode
email: alex@grabcode.fr
description: "Alexandre Girard — Senior Engineering Manager, Co-founder, Full-stack Engineer"
baseurl: ""
url: "http://grabcode.fr"
twitter_username: alxgirard
github_username:  grabcode
author: Alexandre Girard

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: :compressed

collections:
  projects:
    output: true
  cheatsheets:
    output: true
